### ISSUE TITLE
VERSION not found during installation

### ISSUE THREAD

**Issue by davfsa** [mdiller/dotabase#3]
Error gotting when trying to install using `pip install dotabase`

*This error is also on Linux*

```
Collecting dotabase>=4.8.8
  Using cached https://files.pythonhosted.org/packages/40/7f/c94668b048246815f5fc40b113540bad3d98fe09b4b7bf8817ead2e50bbd/dotabase-4.8.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\...\AppData\Local\Temp\pycharm-packaging\dotabase\setup.py", line 12, in <module>
        with open(path.join(path.dirname(__file__), 'VERSION')) as f:
      File "C:\Users\...\AppData\Local\Programs\Python\Python36\lib\codecs.py", line 897, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\...\\AppData\\Local\\Temp\\pycharm-packaging\\dotabase\\VERSION'
    
    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in C:\Users\...\AppData\Local\Temp\pycharm-packaging\dotabase\
```

**Comment by mdiller** [comment]
Whoops, sorry about that. Forgot to update the manifest when I added the new version stuff. Fixed in version 4.8.9! Thanks for letting me know.
